### PR TITLE
User/ter/gcc code updates

### PR DESCRIPTION
**Pull request by thomas-robinson**
This branch fixes some errors that intel allows but gfortran does not.  It also adds a gnu.mk template for compiling.

Addresses #10

### CODE REVIEW

**Comment by thomas-robinson** [comment]
This branch also has updates from #9 in it

**Comment by edwardhartnett** [comment]
Will this branch be merged?

**Comment by thomas-robinson** [comment]
@edwardhartnett I will work on this tomorrow

**Comment by thomas-robinson** [comment]
@edwardhartnett this branch can't be merged.  This is going to have to be reworked.

**Comment by thomas-robinson** [comment]
The conflicts are resolved in #17

**Pull request closed without merging**
